name: Publish package to npmjs
on:
    push:
        branches:
            - 'main'
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x' # Usa una versión actual de Node
                  registry-url: 'https://registry.npmjs.org'
  
            - run: npm ci

            - run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

